version: '3.9'

services:
 postgres:
  image: postgres
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DATABASE}

  ports:
   - 5432:5432
